changed-files-labels-limit: 5
max-files-changed: 100

web:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/web/**'

server:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/server/**'

workspace:
  - changed-files:
      - any-glob-to-any-file:
          - 'mise.toml'
          - '.gitignore'
          - '.vscode/**'
          - '.editorconfig'
          - 'apps/*/.prettierignore'
          - 'apps/*/.prettierrc.json'
          - 'apps/*/.oxlintrc.json'
          - 'apps/*/stylelint.config.*'
          - 'apps/*/tsconfig*.json'
          - 'apps/*/vite.config.*'
          - 'apps/*/go.mod'

assets:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/*/public/**'

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'Dockerfile'
          - 'Dockerfile.*'
          - 'compose.yml'
          - 'compose.yaml'
          - 'docker/**'
          - 'infrastructure/**'

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/*/package.json'
          - '**/go.mod'
          - '**/go.sum'
          - 'apps/*/bun.lock'
          - 'apps/*/package-lock.json'
          - 'apps/*/pnpm-lock.yaml'
          - 'apps/*/yarn.lock'
          - 'mise.toml'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'documentation/**'
          - 'README.md'
          - 'LICENSE'
          - 'LICENSE.*'

environment:
  - changed-files:
      - any-glob-to-any-file:
          - '**/.env.example'
          - '**/.env.*.example'
